//This code is auto generated by gen_textures.py
//use textures.txt to create and edit textures
GTexture* tex_player;
GTexture* Tex_player(){return tex_player;}GTexture* tex_player2;
GTexture* Tex_player2(){return tex_player2;}void create_textures(){tex_player = gpu_createTex(3, 3);
tex_player->Data[0] = false;
tex_player->Data[1] = true;
tex_player->Data[2] = false;
tex_player->Data[3] = true;
tex_player->Data[4] = true;
tex_player->Data[5] = true;
tex_player->Data[6] = false;
tex_player->Data[7] = true;
tex_player->Data[8] = false;
tex_player2 = gpu_createTex(3, 3);
tex_player2->Data[0] = true;
tex_player2->Data[1] = false;
tex_player2->Data[2] = true;
tex_player2->Data[3] = true;
tex_player2->Data[4] = true;
tex_player2->Data[5] = true;
tex_player2->Data[6] = true;
tex_player2->Data[7] = false;
tex_player2->Data[8] = true;
};