//This code is auto generated by gen_textures.py
//use textures.txt to create and edit textures
GTexture* tex_player;

bool tex_player_data[] = {true, false, true, false};


GTexture* Tex_player(){return tex_player;}void create_textures(){tex_player = gpu_createTex(4, 3);
tex_player->Data = tex_player_data;
};



