//This code is auto generated by gen_textures.py
//use textures.txt to create and edit textures
GTexture* tex_player;
GTexture* Tex_player(){return tex_player;}void create_textures(){tex_player = gpu_createTex(4, 3);
tex_player->Data[0] = false;
tex_player->Data[1] = true;
tex_player->Data[2] = true;
tex_player->Data[3] = false;
tex_player->Data[4] = true;
tex_player->Data[5] = true;
tex_player->Data[6] = true;
tex_player->Data[7] = true;
tex_player->Data[8] = false;
tex_player->Data[9] = true;
tex_player->Data[10] = true;
tex_player->Data[11] = false;
};