$OUTPUT_FILE = ".\2_gen_textures.ino"

$global_code = "";
$function_code = "";


$current_tex_name = "";
$current_tex_data = @();
$current_tex_w = 0;
$current_tex_h = 0;


function WriteCurrentTexToCode(){
	echo "a"
	
	

}




foreach($line in Get-Content .\textures.txt) {
    
	$trimmed = $line.Trim();
	
	if ($current_tex_name -eq "" -and -not ($trimmed -eq "")){
		$current_tex_name = $trimmed
		continue;
	}
	
	if ( -not ($current_tex_name -eq "") -and $trimmed -eq ""){
		

		$global_code+="GTexture* tex_$current_tex_name;`n"
	
		$function_code+="tex_$current_tex_name = gpu_createTex($current_tex_w, $current_tex_h);`n"
		for ($i = 0; $i -lt $current_tex_data.Count; $i++){
			$function_code+="tex_$current_tex_name->Data[$i] ="
			$function_code+=$current_tex_data[$i]
			$function_code+=";`n"
		}
		
		$current_tex_name = "";
		$current_tex_data = @();
		$current_tex_w = 0;
		$current_tex_h = 0;
		continue;
	}
	
	$current_tex_w = 0
	$current_tex_h++;
	foreach ($char in $trimmed.ToCharArray()){
		
		if ($char -eq ".")
		{
			$current_tex_w++;
			$current_tex_data+= "false";
		}
		elseif ($char -eq "x" -or $char -eq "X")
		{
			$current_tex_w++;
			$current_tex_data+= "true";
		}
		
	}
		
		

}
WriteCurrentTexToCode

$full_code = "//This code is auto generated by gen_textures.ps1`n"
$full_code += "//use textures.txt to create and edit textures`n"
$full_code += $global_code
$full_code +="void create_textures(){"
$full_code += $function_code
$full_code += "}"

echo $full_code

#Out-File -FilePath $OUTPUT_FILE -InputObject $Procs -Encoding ASCII -Width 50